{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tfl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service: { name: tfl-api, port: { number: 8000 } }
      - path: /
        pathType: Prefix
        backend:
          service: { name: tfl-web, port: { number: 80 } }
{{- end }}
