name: ci-cd
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tfl-api:${{ github.sha }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/web
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tfl-web:${{ github.sha }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name:  ${{ secrets.AKS_NAME }}
      - uses: azure/setup-helm@v4
      - name: Helm upgrade
        run: |
          helm upgrade --install tfl ./charts/tfl \
            --set api.image.repository=ghcr.io/${{ github.repository_owner }}/tfl-api \
            --set api.image.tag=${{ github.sha }} \
            --set web.image.repository=ghcr.io/${{ github.repository_owner }}/tfl-web \
            --set web.image.tag=${{ github.sha }}
